src/inventory/urls.py
from os import name
from django.contrib import admin
from django.urls import path, include
from inventory.index.views import index, addgraph

from inventory.products.views import *
from inventory.users.views import adduser, newuser, listuser, deleteuser, edituser
from inventory.clients.views import list_client, modal_register_client, register_sale, autocomplete_client, autocomplete_upc, insert_product,search_client, delete_temp_product, transacction, transacction_cashier

from inventory.products.views import modify_order_product, create_product_type, list_categories, listproduct, listlot, list_products_supplier, send_order_email, manual_purchase, btn_cancel_an_order, validation_order, list_orders, details_of_order
from inventory.dashboard.views import dashboard
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', index, name='home'),
    path ('nombre/', index, name='path2'),
    path('dashboard/row/graph/add', addgraph,name='add_graph'), 
    #Jonathan
    path('administrator/adduser/', adduser, name='adduser'),
    path('administrator/newuser/', newuser, name='newuser'),
    path('administrator/listuser/', listuser, name='listuser'),
    path('administrator/deleteuser/<int:id>/', deleteuser, name='deleteuser'),
    path('administrator/edituser/<int:id>/', edituser, name='edituser'),
    path('administrator/dashboard/', dashboard, name='dashboard'),


    path('manager/listproduct/', listproduct, name='listproduct'),
    path('manager/manual_purchase/<int:id>/', manual_purchase, name='manual_purchase'),

    path('manager/listlot/<int:id>/', listlot, name='list_lot'),


    
    # Paths para las funciones de manager 
    path('manager/edit_product/<int:id>/', modify_order_product, name='edit_product'),
    path('manager/create_category/', create_category, name='create_category'),
    path('manager/create_supplier/', create_supplier, name='create_supplier'),
    path('manager/create_product_type/', create_product_type, name='type_create'),
    path('manager/list_categories/', list_categories, name='list_categories'),
    path('manager/product_suppliers/<int:id>/', product_suppliers, name='product_suppliers'),
    path('manager/manual_order/<int:id>/<int:nuevo>/', list_products_supplier, name='manual_order'),
    path('manager/remove_product/<int:id_supplier>/<int:id_product_order>/', delete_product_an_order, name='remove_product'),
    path('manager/send_order_email/', send_order_email, name='send_order_email'),
    path('manager/supplier_products/<int:id>/', supplier_products, name='supplier_products'),
    path('manager/suppliers/', suppliers, name='suppliers'),
    path('manager/deletesupplier/<int:id>/', deletesupplier, name='deletesupplier'),
    path('manager/deleteproductsupplier/<int:id>/<int:id2>/', deleteproductsupplier, name='deleteproductsupplier'),
    path('manager/btn_cancel_an_order/<int:id>', btn_cancel_an_order, name='btn_cancel_an_order'),
    path('manager/list_orders/', list_orders, name='list_orders'),
    path('manager/list_detail/<int:id>', details_of_order, name='list_detail'),
    path('manager/cancel_order/<int:id>/', cancel_order, name="cancel_order"),
    # Paths para el cajero
    path('confirm_order/<str:key>/<int:id>', validation_order, name='validation_order'),
    path('cashier/register_client/', modal_register_client, name='register_client'),
    path('cashier/register_sale/', register_sale, name='register_sale'),
    path('api/autocomplete_client/', autocomplete_client, name='autocomplete_client'),
    path('api/autocomplete_upc/', autocomplete_upc, name='autocomplete_upc'),
    path('api/insert_product/', insert_product, name='insert_product'),
    path('client/search_client/', search_client, name='search_client'),
    path('client/delete_temp_product/', delete_temp_product, name='delete_temp_product'),
    path('cashier/list_client', list_client, name='list-client'),
    path('cashier/transactions/', transacction_cashier, name='transactions-cashier'),
    path('administrator/transactions_manager/', transacction, name='transactions')
    
]

src/inventory/common/models.py
from django.db import models

src/inventory/products/models.py
from django.db import models
from django.db.models.deletion import CASCADE, SET_NULL
from django.utils.timezone import now

class Category (models.Model):
    id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=100)

    def __str__(self):
        return "%s" % (self.name)
    
class Supplier(models.Model):
    id=models.AutoField(primary_key=True)
    email=models.CharField(max_length=200, unique=True)
    name=models.CharField(max_length=200)
    active =models.BooleanField(default=True)
    address=models.CharField(max_length=200)
    phone=models.CharField(max_length=20)

    def __str__(self):
        return "%s" % (self.name)



class ProductType (models.Model):
    id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=200, unique=True)
    orderpoint=models.IntegerField(null=True)
    orderquantity=models.IntegerField(null=True)
    quantity=models.IntegerField(default=0)
    category=models.ForeignKey(Category, on_delete=CASCADE, related_name='Category_Products')
    default_supplier=models.ForeignKey(Supplier,null=True, on_delete=SET_NULL, related_name='Default_Supplier')
    order_in_progress=models.BooleanField(default=False,null=True)

    def __str__(self):
        return "%s" % (self.name)
    
    def get_edit_url(self):
        return 'edit_product/'+str(self.id)+"/"


class SalePrice(models.Model):
    id=models.AutoField(primary_key=True)
    channgeddate=models.DateTimeField()
    price=models.DecimalField(max_digits=8, decimal_places=2)
    producttype=models.ForeignKey(ProductType, on_delete=CASCADE, related_name='ProductType_SalesPrice')


class ProductSupplier(models.Model):
    id=models.AutoField(primary_key=True)
    supplier=models.ForeignKey(Supplier, on_delete=CASCADE, related_name='Supplier_Producttype')
    producttype=models.ForeignKey(ProductType, on_delete=CASCADE, related_name='Producttype_Supplier')

class GroupProduct(models.Model):
    upc=models.AutoField(primary_key=True)
    ingressdate=models.DateTimeField(default=now)
    expirationdate=models.DateTimeField()
    quantity=models.IntegerField()
    producttype=models.ForeignKey(ProductType, on_delete=CASCADE, related_name='ProductType_GropuProducts')
    supplier=models.ForeignKey(Supplier, on_delete=CASCADE, related_name='Supplier_GropuProducts')

class Order(models.Model):
    id=models.AutoField(primary_key=True)
    orderdate=models.DateTimeField(default=now)
    state=models.CharField(max_length=200, default='No Completado')
    validation_key=models.CharField(max_length=200)
    supplier=models.ForeignKey(Supplier, on_delete=CASCADE, related_name='Order_Supplier')

class Order_Products(models.Model):
    id=models.AutoField(primary_key=True)
    quantity=models.IntegerField()
    date=models.DateTimeField(null=True)
    producttype=models.ForeignKey(ProductType, on_delete=CASCADE, related_name='Order_Producttype')
    numberoforder=models.ForeignKey(Order, on_delete=CASCADE, related_name='Number_Order')

src/inventory/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Rol(models.Model):

    id=models.AutoField(primary_key=True)
    rol=models.CharField('Rol', max_length=50, unique=True)

    class Meta:
        verbose_name= 'Rol'
        verbose_name_plural= 'Roles'

    def __str__(self):
        return self.rol
    def get_rol(self):
        return self.rol

class User (AbstractUser):
    rol=models.ForeignKey(Rol, on_delete=models.CASCADE, blank=True, null=True, default=1)

    def get_delete_url(self):
        return 'deleteuser/'+str(self.id)+"/"

    def get_edit_url(self):
        return 'edituser/'+str(self.id)+"/"

src/inventory/clients/views.py
from django.db.models.aggregates import Sum
from django.shortcuts import redirect, render
from django.contrib import messages
from django.http import JsonResponse

from inventory.products.views import automatic_order
from .models import Client, TempProductSale, Sale, ProductSale
from datetime import datetime
from inventory.products.models import GroupProduct,SalePrice,ProductType
from inventory.users.models import User
from .forms import ClientForm
import json
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from decimal import *
from django.db import transaction

# Create your views here.

def modal_register_client(request): # Bryan - 1
    exist = False
    clients = Client.objects.all()
    if request.method == 'GET':
        context = {
            'success':exist
        }
    else:
        exist = check_exist_nit(clients, request.POST.get('nit'))
        if exist:
            context = {
                'success':exist,
                'name_client':request.POST.get('name'),
                'last_name_client':request.POST.get('last_name'),
                'address_client':request.POST.get('address'),
                'phone_client':request.POST.get('phone'),
                'nit_repeat':request.POST.get('nit')
            }
        else:
            client = ClientForm(request.POST)
            if client.is_valid():
                client.save()
                messages.success(request, "Cliente \"" + request.POST.get('name') + "\" Agregado")
                return redirect('home')
            else:
                context = {'success':True}
    return render(request,"cashier/client/register_client.html",context)

def check_exist_nit(clients, compare):
    for client  in clients:
        if client.nit == compare:
            return True
    return False
    
def register_sale(request):
    if request.method == 'GET':
         TempProductSale.objects.all().delete()
    if request.method == 'POST':
        nit=request.POST.get('client_nit')
        if(nit=="C/F" or nit==""):
            client=Client.objects.get(nit="C/F")   
        elif Client.objects.filter(nit = nit).exists():
            client=Client.objects.get(nit = nit)
        else:      
            messages.error(request,'Cliente no existe')
            return render(request,"cashier/register_sale.html") 
        temps=TempProductSale.objects.all()
        if(temps.count()>0):
            user=User.objects.get(username=request.POST.get('user'))
            new_sale=Sale(client=client,cashier=user,datetime=datetime.now(),total=get_temp_total())
            new_sale.save()
            for temp in temps:
                new_product_sale=ProductSale(product=temp.product,sale=new_sale,quantity=temp.quantity,total=temp.total)
                new_product_sale.save()
                remove_products_from_stock(temp.quantity,temp.product)
                if temp.product.producttype.order_in_progress==False:
                    verify_automatic_order(temp.product.producttype)
            messages.info(request, 'Compra Realizada Correctamente')
            TempProductSale.objects.all().delete()    
                
        else:
            messages.error(request,'No existen productos seleccionados')
    groupProduct=GroupProduct.objects.all().order_by("producttype") 
    #print(groupProduct)      
    context={"products":groupProduct}
    return render(request,"cashier/register_sale.html",context)   

def verify_automatic_order(producttype):
    if producttype.quantity<=producttype.orderpoint and producttype.default_supplier != None:
        if automatic_order(producttype):
            producttype.order_in_progress = True
            producttype.save()

@transaction.atomic
def remove_products_from_stock(quantity,productgroup):
    productgroup.quantity=productgroup.quantity-quantity
    productgroup.producttype.quantity=productgroup.producttype.quantity-quantity
    productgroup.save()
    productgroup.producttype.save()

def autocomplete_upc(request):
    if request.is_ajax():
        query = request.GET.get("term", "")
        products = get_upc_for_autocomplete(query)
        titles = list()
        for product in products:
            titles.append(str(product.upc))
        data = json.dumps(titles)
    mimetype = "application/json"
    return HttpResponse(data, mimetype)

def get_upc_for_autocomplete(term):
    return GroupProduct.objects.filter(upc__icontains=term)

def autocomplete_client(request):
    if request.is_ajax():
        query = request.GET.get("term", "")
        clients = get_nit_for_autocomplete(query)
        
        titles = list()
        for product in clients:
            titles.append(product.nit)
        data = json.dumps(titles)
    mimetype = "application/json"
    return HttpResponse(data, mimetype)

def get_nit_for_autocomplete(term):
    return Client.objects.filter(nit__icontains=term)

@csrf_exempt
def insert_product(request):
    data=request.POST.get("data")
    upc=request.POST.get("upc")
    quantity=request.POST.get("quantity")
    number=TempProductSale.objects.all().count()+1
    if upc=="" or not upc.isnumeric() or not GroupProduct.objects.filter(upc=upc).exists():
        response_data={"error":True,"errorMessage":"UPC invalido"}
        return JsonResponse(response_data,safe=False)
    group=GroupProduct.objects.get(upc=upc)
    product_name=group.producttype.name
    saleprice=SalePrice.objects.filter(producttype=group.producttype).order_by('-channgeddate').first()
    total=get_total(quantity,saleprice)
    temps=TempProductSale.objects.filter(product=group)
    
    aux=0
    for temp in temps:
        aux+=temp.quantity
        
    if (int(quantity)+aux)>group.quantity:
        response_data={"error":True,"errorMessage":"Cantidad no disponible en inventario"}
        return JsonResponse(response_data,safe=False)
    else:

    #Creates temp model
        tempSale=TempProductSale(number=number,product=group,quantity=quantity,total=total)
        tempSale.save()
        
        temp_total=get_temp_total()
        try:
            productsale={"upc":upc,
                            "quantity":quantity,
                            "saleprice":str(saleprice.price),
                            "product_name":product_name,
                            "number":str(number),
                            "total":total}
            response_data={"productsale": productsale,"error":False,"errorMessage":"Updated Successfully","temp_total":str(temp_total)}
            return JsonResponse(response_data,safe=False)
        except:
            response_data={"error":True,"errorMessage":"Failed to Update Data"}
            return JsonResponse(response_data,safe=False)

def get_total(quantity, saleprice):
    return Decimal(quantity)*Decimal(saleprice.price)

def get_temp_total():
    total=0
    temps=TempProductSale.objects.all()
    for temp in temps:
        total+=temp.total
    return total


@csrf_exempt
def search_client(request):
    client_nit=request.POST.get("client_nit")
    if Client.objects.filter(nit = client_nit).exists():
        client=Client.objects.get(nit = client_nit)
        clientInfo={"name":str(client),
                        "phone":client.phone}
        try:
            response_data={"clientInfo": clientInfo,"error":False,"errorMessage":"Updated Successfully"}
            return JsonResponse(response_data,safe=False)
        except:
            response_data={"error":True,"errorMessage":"Failed to Update Data"}
            return JsonResponse(response_data,safe=False)
    else:
        try:
            response_data={"error":True,"errorMessage":"Cliente no existe"}
            return JsonResponse(response_data,safe=False)
        except:
            response_data={"error":True,"errorMessage":"Failed to get Client info"}
            return JsonResponse(response_data,safe=False)

@csrf_exempt
def delete_temp_product(request):
    data=request.POST.get("number")
    product_number=data
    temp=TempProductSale.objects.get(number=product_number)
    temp.delete()
    response_data={"error":False,"errorMessage":"Updated Successfully","temp_total":str(get_temp_total())}
    return JsonResponse(response_data,safe=False)

def list_client(request):
    context = { 'clients':Client.objects.all() }
    return render (request, "cashier/client/list-client.html", context)

def transacction_cashier(request):
    transactions = Sale.objects.filter(cashier=request.user).filter(datetime__gte=datetime.today().replace(hour=00).replace(minute=00).replace(second=00))
    total = transactions.aggregate(total_price=Sum('total'))['total_price']
    
    context = {
        'date':datetime.now(),
        'transactions':transactions,
        'total':total
    }
    if request.method == 'POST':
        if request.POST.get('date-time'):
            transactions = Sale.objects.filter(cashier=request.user).filter(datetime__lte=request.POST.get('date-time'))
            total = transactions.aggregate(total_price=Sum('total'))['total_price']
            context = {
                'date':request.POST.get('date-time'),
                'transactions':transactions,
                'total':total
            }
    return render (request, "cashier/list-transactions.html", context)

def transacction(request):
    transactions = Sale.objects.all().filter(datetime__gte=datetime.today().replace(hour=00).replace(minute=00).replace(second=00))
    #print ((transactions[0].cashier))
    total = transactions.aggregate(total_price=Sum('total'))['total_price']
    
    context = {
        'date':datetime.now(),
        'transactions':transactions,
        'total':total
    }
    if request.method == 'POST':
        if request.POST.get('date-time'):
            transactions = Sale.objects.filter(cashier=request.user).filter(datetime__lte=request.POST.get('date-time'))
            total = transactions.aggregate(total_price=Sum('total'))['total_price']
            context = {

src/inventory/templates/administrator/adduser.html
{% extends "inventory_base.html" %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block extra_css %}
{% endblock %}

{% block content %}
<!-- Start Content-->
<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    
                </div>
                <h4 class="page-title"><i data-feather="user-plus"></i>  AÑADIR USUARIOS</h4>
            </div>
        </div>
    </div>     
    <!-- end page title --> 
    <!--Body-->


    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <div class="card" style="border-radius: 25px;">
                    <div class="card-body p-4">
                        <!-- Logo-->
                        <div class="text-center w-75 m-auto">
                          <div class="auth-logo">
                            <a href="" class="logo logo-dark text-center">
                                <span class="logo-lg">
                                    <img src="/static/images/DashTory.png" alt="" height="50">
                                </span>
                            </a>
                
                            <a href="" class="logo logo-light text-center">
                                <span class="logo-lg">
                                    <img src="/static/images/DashTory.png" alt="" height="50">
                                </span>
                            </a>
                          </div>
                          <p class="text-muted mb-4 mt-3">Crear un nuevo Usuario</p>
                      </div>
                        <form action="{% url 'newuser' %}" method="POST", enctype="multipart/form-data">
                            {% csrf_token %}
                            <input type="hidden" name="id_row" value={{ row.id }}>
                                    {% if form.errors %}
                                        {% for field in form %}
                                            {% for error in field.errors %}
                                                <div class="alert alert-danger">
                                                    <strong>{{ error|escape }}</strong>
                                                </div>
                                            {% endfor %}
                                        {% endfor %}
                                        {% for error in form.non_field_errors %}
                                            <div class="alert alert-danger">
                                                <strong>{{ error|escape }}</strong>
                                            </div>
                                        {% endfor %}
                                    {% endif %}
                                    {{ form | crispy }} 
                            <br>
                            <div style="text-align: end;">
                                <button type="submit" class="btn btn-primary">Crear</button>
                            </div>
                        </form>
                      </div>
                      
            </div>
        </div>
    </div> 



    






















    <!--End Body-->       
</div>
<!-- container -->
{% endblock %}
{% block extra_javascript %}

{% endblock%}

src/inventory/templates/administrator/edituser.html
{% extends "inventory_base.html" %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block extra_css %}
{% endblock %}

{% block content %}
<!-- Start Content-->
<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    
                </div>
                <h4 class="page-title"><i data-feather="user-plus"></i>  EDITAR USUARIO</h4>
            </div>
        </div>
    </div>     
    <!-- end page title --> 
    <!--Body-->


    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <div class="card" style="border-radius: 25px;">
                    <div class="card-body p-4">
                        <!-- Logo-->
                        <div class="text-center w-75 m-auto">
                          <div class="auth-logo">
                            <a href="" class="logo logo-dark text-center">
                                <span class="logo-lg">
                                    <img src="/static/images/DashTory.png" alt="" height="50">
                                </span>
                            </a>
                
                            <a href="" class="logo logo-light text-center">
                                <span class="logo-lg">
                                    <img src="/static/images/DashTory.png" alt="" height="50">
                                </span>
                            </a>
                          </div>
                          <p class="text-muted mb-4 mt-3">Editando al Usuario</p>
                      </div>
                        <form method="POST", enctype="multipart/form-data">
                            {% csrf_token %}                                                
                            <div id="div_id_email" class="mb-3"> <label for="id_email" class="form-label">Email address</label> 
                                <input type="email" name="email" maxlength="254" class="emailinput form-control" id="id_email" value="{{ user.email }}"> 
                            </div> 
                            <div id="div_id_username" class="mb-3"> <label for="id_username" class="form-label requiredField">Username<span class="asteriskField">*</span> </label> 
                                <input type="text" name="username" maxlength="150" class="textinput textInput form-control" required id="id_username" value="{{ user.username }}"> <small id="hint_id_username" class="form-text text-muted">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small>
                            </div> 
                            <div id="div_id_rol" class="mb-3"> <label for="id_rol" class="form-label requiredField">Rol<span class="asteriskField">*</span> </label>
                                <select name="rol" class="select form-select" required id="id_rol"> 
                                    {% for rol in roles %} 
                                        {% if user.rol.id == rol.id %}
                                            <option value="{{ rol.id }}" selected>{{ rol.rol }}</option> 
                                        {% else%}
                                            <option value="{{ rol.id }}">{{ rol.rol }}</option> 
                                        {% endif %}
                                    {% endfor %}
                                </select> 
                            </div> 
                            <br>

                            <div class="row">
                                <div class="col">
                                    <div style="text-align:initial;">
                                        <a href="{% url 'listuser' %}" class="btn btn-danger">Cancelar</a>
                                    </div>
                                </div>
                                <div class="col">
                                    <div style="text-align: end;">
                                        <button type="submit" class="btn btn-primary">Guardar</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
            </div>
        </div>
    </div> 



    






















    <!--End Body-->       
</div>
<!-- container -->
{% endblock %}
{% block extra_javascript %}

{% endblock%}

src/inventory/templates/administrator/listuser.html
{% extends "inventory_base.html" %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block extra_css %}
{% endblock %}

{% block content %}
<!-- Start Content-->
<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    
                </div>
                <h4 class="page-title"><i data-feather="user"></i> LISTA DE USUARIOS</h4>
            </div>
        </div>
    </div>     
    <!-- end page title --> 
    <!--Body-->


    <div class="row" style="padding-left: 3em; padding-right: 3em;">
        <div class="card" style="border-radius: 25px;">
            <div class="card-body p-4">



        <table id="example" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>User Name</th>
                    <th>Email</th>
                    <th>Rol</th>
                    <th style="width: 6em; text-align: center;">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr>
                    <td>{{ user.id }}</td>
                    <td>{{ user.username }}</td>
                    <td>{{ user.email }}</td>
                    <td>
                        {% if user.rol.id == 1 %}
                        <span class="badge bg-soft-primary text-primary" style="font-size: 0.85em"><b>{{ user.rol }}</b></span>
                        {% elif user.rol.id == 2 %}
                        <span class="badge bg-soft-info text-info" style="font-size: 0.85em"><b>{{ user.rol }}</b></span>
                        {% else %}
                        <span class="badge bg-soft-success text-success" style="font-size: 0.85em"><b>{{ user.rol }}</b></span>
                        {% endif %}
                    </td>
                    <td style="text-align: center;">    
                        <small style="font-size: 1.5em"><a href="../{{user.get_edit_url}}"><i class="fe-edit" title="Editar"></i></a></small>
                        <small style="font-size: 1.5em"><a href="../{{user.get_delete_url}}" title="Eliminar" class="delete" onclick="return confirm('Are you sure you want to delete this item')"><i class="fe-trash-2"></i></a></small>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>


        </div>
        </div>














        
    </div> 

    <!--End Body-->       
</div>
<!-- container -->
{% endblock %}
{% block extra_javascript %}
<script>
    $(document).ready(function() {
        $('#example').DataTable().addClass("pagination-rounded");
    } );
</script>

{% endblock%}