src/inventory/urls.py
from os import name
from django.contrib import admin
from django.urls import path, include
from inventory.index.views import index, addgraph

from inventory.products.views import *
from inventory.users.views import adduser, newuser, listuser, deleteuser, edituser
from inventory.clients.views import list_client, modal_register_client, register_sale, autocomplete_client, autocomplete_upc, insert_product,search_client, delete_temp_product, transacction, transacction_cashier

from inventory.products.views import modify_order_product, create_product_type, list_categories, listproduct, listlot, list_products_supplier, send_order_email, manual_purchase, btn_cancel_an_order, validation_order, list_orders, details_of_order
from inventory.dashboard.views import dashboard
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', index, name='home'),
    path ('nombre/', index, name='path2'),
    path('dashboard/row/graph/add', addgraph,name='add_graph'), 
    #Jonathan
    path('administrator/adduser/', adduser, name='adduser'),
    path('administrator/newuser/', newuser, name='newuser'),
    path('administrator/listuser/', listuser, name='listuser'),
    path('administrator/deleteuser/<int:id>/', deleteuser, name='deleteuser'),
    path('administrator/edituser/<int:id>/', edituser, name='edituser'),
    path('administrator/dashboard/', dashboard, name='dashboard'),


    path('manager/listproduct/', listproduct, name='listproduct'),
    path('manager/manual_purchase/<int:id>/', manual_purchase, name='manual_purchase'),

    path('manager/listlot/<int:id>/', listlot, name='list_lot'),


    
    # Paths para las funciones de manager 
    path('manager/edit_product/<int:id>/', modify_order_product, name='edit_product'),
    path('manager/create_category/', create_category, name='create_category'),
    path('manager/create_supplier/', create_supplier, name='create_supplier'),
    path('manager/create_product_type/', create_product_type, name='type_create'),
    path('manager/list_categories/', list_categories, name='list_categories'),
    path('manager/product_suppliers/<int:id>/', product_suppliers, name='product_suppliers'),
    path('manager/manual_order/<int:id>/<int:nuevo>/', list_products_supplier, name='manual_order'),
    path('manager/remove_product/<int:id_supplier>/<int:id_product_order>/', delete_product_an_order, name='remove_product'),
    path('manager/send_order_email/', send_order_email, name='send_order_email'),
    path('manager/supplier_products/<int:id>/', supplier_products, name='supplier_products'),
    path('manager/suppliers/', suppliers, name='suppliers'),
    path('manager/deletesupplier/<int:id>/', deletesupplier, name='deletesupplier'),
    path('manager/deleteproductsupplier/<int:id>/<int:id2>/', deleteproductsupplier, name='deleteproductsupplier'),
    path('manager/btn_cancel_an_order/<int:id>', btn_cancel_an_order, name='btn_cancel_an_order'),
    path('manager/list_orders/', list_orders, name='list_orders'),
    path('manager/list_detail/<int:id>', details_of_order, name='list_detail'),
    path('manager/cancel_order/<int:id>/', cancel_order, name="cancel_order"),
    # Paths para el cajero
    path('confirm_order/<str:key>/<int:id>', validation_order, name='validation_order'),
    path('cashier/register_client/', modal_register_client, name='register_client'),
    path('cashier/register_sale/', register_sale, name='register_sale'),
    path('api/autocomplete_client/', autocomplete_client, name='autocomplete_client'),
    path('api/autocomplete_upc/', autocomplete_upc, name='autocomplete_upc'),
    path('api/insert_product/', insert_product, name='insert_product'),
    path('client/search_client/', search_client, name='search_client'),
    path('client/delete_temp_product/', delete_temp_product, name='delete_temp_product'),
    path('cashier/list_client', list_client, name='list-client'),
    path('cashier/transactions/', transacction_cashier, name='transactions-cashier'),
    path('administrator/transactions_manager/', transacction, name='transactions')
    
]

src/inventory/clients/models.py
from django.db import models
from ..users.models import User
from django.db.models.deletion import CASCADE, SET_NULL
from ..products.models import GroupProduct
# Create your models here.

class Client(models.Model):
    id=models.AutoField(primary_key=True)
    nit=models.CharField(unique=True, max_length=20, null=True)
    name=models.CharField(max_length=200)
    last_name=models.CharField(max_length=200, null=True)
    address=models.CharField(max_length=200, null=True)
    phone=models.CharField(max_length=20, null=True)

    def __str__(self):
        return self.name+" "+self.last_name

class Sale(models.Model):
    id=models.AutoField(primary_key=True)
    client=models.ForeignKey(Client,on_delete=SET_NULL,null=True, related_name='Sale_Client')
    cashier=models.ForeignKey(User,on_delete=CASCADE, related_name='Sale_Cashier')
    datetime=models.DateTimeField()
    total=models.DecimalField(max_digits=8, decimal_places=2)

class ProductSale(models.Model):
    id=models.AutoField(primary_key=True)
    product=models.ForeignKey(GroupProduct,on_delete=CASCADE, related_name='Sale_Cashier')
    sale=models.ForeignKey(Sale,on_delete=CASCADE, related_name='ProductSale_Sale')
    quantity=models.IntegerField(default = 1)
    total=models.DecimalField(max_digits=8, decimal_places=2)

class TempProductSale(models.Model):
    id=models.AutoField(primary_key=True)
    number=models.IntegerField()
    product=models.ForeignKey(GroupProduct,on_delete=CASCADE, related_name='Temp_Sale_Cashier')
    quantity=models.IntegerField(default = 1)
    total=models.DecimalField(max_digits=8, decimal_places=2)

src/inventory/common/models.py
from django.db import models

src/inventory/clients/views.py
from django.db.models.aggregates import Sum
from django.shortcuts import redirect, render
from django.contrib import messages
from django.http import JsonResponse

from inventory.products.views import automatic_order
from .models import Client, TempProductSale, Sale, ProductSale
from datetime import datetime
from inventory.products.models import GroupProduct,SalePrice,ProductType
from inventory.users.models import User
from .forms import ClientForm
import json
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from decimal import *
from django.db import transaction

# Create your views here.

def modal_register_client(request): # Bryan - 1
    exist = False
    clients = Client.objects.all()
    if request.method == 'GET':
        context = {
            'success':exist
        }
    else:
        exist = check_exist_nit(clients, request.POST.get('nit'))
        if exist:
            context = {
                'success':exist,
                'name_client':request.POST.get('name'),
                'last_name_client':request.POST.get('last_name'),
                'address_client':request.POST.get('address'),
                'phone_client':request.POST.get('phone'),
                'nit_repeat':request.POST.get('nit')
            }
        else:
            client = ClientForm(request.POST)
            if client.is_valid():
                client.save()
                messages.success(request, "Cliente \"" + request.POST.get('name') + "\" Agregado")
                return redirect('home')
            else:
                context = {'success':True}
    return render(request,"cashier/client/register_client.html",context)

def check_exist_nit(clients, compare):
    for client  in clients:
        if client.nit == compare:
            return True
    return False
    
def register_sale(request):
    if request.method == 'GET':
         TempProductSale.objects.all().delete()
    if request.method == 'POST':
        nit=request.POST.get('client_nit')
        if(nit=="C/F" or nit==""):
            client=Client.objects.get(nit="C/F")   
        elif Client.objects.filter(nit = nit).exists():
            client=Client.objects.get(nit = nit)
        else:      
            messages.error(request,'Cliente no existe')
            return render(request,"cashier/register_sale.html") 
        temps=TempProductSale.objects.all()
        if(temps.count()>0):
            user=User.objects.get(username=request.POST.get('user'))
            new_sale=Sale(client=client,cashier=user,datetime=datetime.now(),total=get_temp_total())
            new_sale.save()
            for temp in temps:
                new_product_sale=ProductSale(product=temp.product,sale=new_sale,quantity=temp.quantity,total=temp.total)
                new_product_sale.save()
                remove_products_from_stock(temp.quantity,temp.product)
                if temp.product.producttype.order_in_progress==False:
                    verify_automatic_order(temp.product.producttype)
            messages.info(request, 'Compra Realizada Correctamente')
            TempProductSale.objects.all().delete()    
                
        else:
            messages.error(request,'No existen productos seleccionados')
    groupProduct=GroupProduct.objects.all().order_by("producttype") 
    #print(groupProduct)      
    context={"products":groupProduct}
    return render(request,"cashier/register_sale.html",context)   

def verify_automatic_order(producttype):
    if producttype.quantity<=producttype.orderpoint and producttype.default_supplier != None:
        if automatic_order(producttype):
            producttype.order_in_progress = True
            producttype.save()

@transaction.atomic
def remove_products_from_stock(quantity,productgroup):
    productgroup.quantity=productgroup.quantity-quantity
    productgroup.producttype.quantity=productgroup.producttype.quantity-quantity
    productgroup.save()
    productgroup.producttype.save()

def autocomplete_upc(request):
    if request.is_ajax():
        query = request.GET.get("term", "")
        products = get_upc_for_autocomplete(query)
        titles = list()
        for product in products:
            titles.append(str(product.upc))
        data = json.dumps(titles)
    mimetype = "application/json"
    return HttpResponse(data, mimetype)

def get_upc_for_autocomplete(term):
    return GroupProduct.objects.filter(upc__icontains=term)

def autocomplete_client(request):
    if request.is_ajax():
        query = request.GET.get("term", "")
        clients = get_nit_for_autocomplete(query)
        
        titles = list()
        for product in clients:
            titles.append(product.nit)
        data = json.dumps(titles)
    mimetype = "application/json"
    return HttpResponse(data, mimetype)

def get_nit_for_autocomplete(term):
    return Client.objects.filter(nit__icontains=term)

@csrf_exempt
def insert_product(request):
    data=request.POST.get("data")
    upc=request.POST.get("upc")
    quantity=request.POST.get("quantity")
    number=TempProductSale.objects.all().count()+1
    if upc=="" or not upc.isnumeric() or not GroupProduct.objects.filter(upc=upc).exists():
        response_data={"error":True,"errorMessage":"UPC invalido"}
        return JsonResponse(response_data,safe=False)
    group=GroupProduct.objects.get(upc=upc)
    product_name=group.producttype.name
    saleprice=SalePrice.objects.filter(producttype=group.producttype).order_by('-channgeddate').first()
    total=get_total(quantity,saleprice)
    temps=TempProductSale.objects.filter(product=group)
    
    aux=0
    for temp in temps:
        aux+=temp.quantity
        
    if (int(quantity)+aux)>group.quantity:
        response_data={"error":True,"errorMessage":"Cantidad no disponible en inventario"}
        return JsonResponse(response_data,safe=False)
    else:

    #Creates temp model
        tempSale=TempProductSale(number=number,product=group,quantity=quantity,total=total)
        tempSale.save()
        
        temp_total=get_temp_total()
        try:
            productsale={"upc":upc,
                            "quantity":quantity,
                            "saleprice":str(saleprice.price),
                            "product_name":product_name,
                            "number":str(number),
                            "total":total}
            response_data={"productsale": productsale,"error":False,"errorMessage":"Updated Successfully","temp_total":str(temp_total)}
            return JsonResponse(response_data,safe=False)
        except:
            response_data={"error":True,"errorMessage":"Failed to Update Data"}
            return JsonResponse(response_data,safe=False)

def get_total(quantity, saleprice):
    return Decimal(quantity)*Decimal(saleprice.price)

def get_temp_total():
    total=0
    temps=TempProductSale.objects.all()
    for temp in temps:
        total+=temp.total
    return total


@csrf_exempt
def search_client(request):
    client_nit=request.POST.get("client_nit")
    if Client.objects.filter(nit = client_nit).exists():
        client=Client.objects.get(nit = client_nit)
        clientInfo={"name":str(client),
                        "phone":client.phone}
        try:
            response_data={"clientInfo": clientInfo,"error":False,"errorMessage":"Updated Successfully"}
            return JsonResponse(response_data,safe=False)
        except:
            response_data={"error":True,"errorMessage":"Failed to Update Data"}
            return JsonResponse(response_data,safe=False)
    else:
        try:
            response_data={"error":True,"errorMessage":"Cliente no existe"}
            return JsonResponse(response_data,safe=False)
        except:
            response_data={"error":True,"errorMessage":"Failed to get Client info"}
            return JsonResponse(response_data,safe=False)

@csrf_exempt
def delete_temp_product(request):
    data=request.POST.get("number")
    product_number=data
    temp=TempProductSale.objects.get(number=product_number)
    temp.delete()
    response_data={"error":False,"errorMessage":"Updated Successfully","temp_total":str(get_temp_total())}
    return JsonResponse(response_data,safe=False)

def list_client(request):
    context = { 'clients':Client.objects.all() }
    return render (request, "cashier/client/list-client.html", context)

def transacction_cashier(request):
    transactions = Sale.objects.filter(cashier=request.user).filter(datetime__gte=datetime.today().replace(hour=00).replace(minute=00).replace(second=00))
    total = transactions.aggregate(total_price=Sum('total'))['total_price']
    
    context = {
        'date':datetime.now(),
        'transactions':transactions,
        'total':total
    }
    if request.method == 'POST':
        if request.POST.get('date-time'):
            transactions = Sale.objects.filter(cashier=request.user).filter(datetime__lte=request.POST.get('date-time'))
            total = transactions.aggregate(total_price=Sum('total'))['total_price']
            context = {
                'date':request.POST.get('date-time'),
                'transactions':transactions,
                'total':total
            }
    return render (request, "cashier/list-transactions.html", context)

def transacction(request):
    transactions = Sale.objects.all().filter(datetime__gte=datetime.today().replace(hour=00).replace(minute=00).replace(second=00))
    #print ((transactions[0].cashier))
    total = transactions.aggregate(total_price=Sum('total'))['total_price']
    
    context = {
        'date':datetime.now(),
        'transactions':transactions,
        'total':total
    }
    if request.method == 'POST':
        if request.POST.get('date-time'):
            transactions = Sale.objects.filter(cashier=request.user).filter(datetime__lte=request.POST.get('date-time'))
            total = transactions.aggregate(total_price=Sum('total'))['total_price']
            context = {

src/inventory/index/views.py
from django.shortcuts import render, redirect
import json
from django.contrib import messages

from inventory.index.forms import UsersForm

# Create your views here.


def index(request):
    option=[]
    name=[]
    option.append('{"title": {"text": "ejempo_0"},"xAxis": {"type": "category","data": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]},"yAxis": {"type": "value"},"series": [{"data": [150, 230, 224, 218, 135, 147, 260],"type": "line","name": "uno"},{"data": [160, 220, 214, 228, 145, 157, 270],"type": "line","name": "dos"}]}')
    option.append('{"title": {"text": "ejempo_1"},"xAxis": {"type": "category","data": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]},"yAxis": {"type": "value"},"series": [{"data": [150, 230, 224, 218, 135, 147, 260],"type": "line","name": "uno"},{"data": [160, 220, 214, 228, 145, 157, 270],"type": "line","name": "dos"}]}')
    option.append('{"title": {"text": "ejempo_2"},"xAxis": {"type": "category","data": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]},"yAxis": {"type": "value"},"series": [{"data": [150, 230, 224, 218, 135, 147, 260],"type": "line","name": "uno"},{"data": [160, 220, 214, 228, 145, 157, 270],"type": "line","name": "dos"}]}')
    name.append('id_0')
    name.append('id_1')
    name.append('id_2')
    json_option = json.dumps(option)
    json_name = json.dumps(name)
    nombre='Jonathan'
    #messages.success(request, "Registration successful." )
    form = UsersForm(request.POST or None, request.FILES or None)
    context = {
        'options' :json_option ,
        'names':json_name,
        'nombre': nombre,
        'form' : form,
    }
    if (request.user.rol.id==1):
        return redirect ('dashboard')
    elif(request.user.rol.id==2):
        return redirect ('listproduct')
    else:
        return redirect ('register_sale')

    #return render(request, "index/index.html", context) 


def addgraph(request):
    form = UsersForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        messages.success(request, "Formulario")
        return redirect ('/')
        

src/inventory/templates/manager/orders/detail_order.html
{% extends "inventory_base.html" %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block extra_css %}
{% endblock %}

{% block content %}
<!-- Start Content-->
<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    
                </div>
                <h4 class="page-title"><i data-feather="list"></i> Lista de productos</h4>
            </div>
        </div>
    </div>     
    <!-- end page title --> 
    <!--Body-->

    <div class="row" style="padding-left: 3em; padding-right: 3em;">
        <div class="card" style="border-radius: 25px;">
            <div class="card-body p-4">

                <div class="row">
                    <center>
                        <h2><b>Detalle de productos solicitados a: <b>{{ supplier }}</b></b> </h2>
                    </center>
                </div>
                

                <br>
                <div class="row">
                    <h4><b>Pedido: No. </b> {{ id_order }}</h4>
                </div>
                <div class="row">
                    <h4><b>Fecha: </b> {{ date }}</h4>
                </div>
                <div class="row">
                    <h4><b>Estado: </b> 
                        {% if state == "No Completado" %}
                            <span class="badge bg-soft-secondary text-secondary" style="font-size: 0.85em"><b>{{ state  }}</b></span>
                        {% elif state == "En Proceso" %}
                            <span class="badge bg-soft-info text-info" style="font-size: 0.85em"><b>{{ state  }}</b></span>
                        {% elif state == "Enviado" %}
                            <span class="badge bg-soft-warning text-warning" style="font-size: 0.85em"><b>{{ state  }}</b></span>
                        {% elif state == "Procesado" %}
                            <span class="badge bg-soft-success text-success" style="font-size: 0.85em"><b>{{ state  }}</b></span>
                        {% else %}
                            <span class="badge bg-soft-danger text-danger" style="font-size: 0.85em"><b>{{ state  }}</b></span>
                        {% endif %}</h4>
                </div>
                <br>
                    <!-- Tablas -->
                    <table id="list_product_order" class="table table-striped table-bordered" style="width:100%">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Producto</th>
                                <th>Cantidad Solicitada</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for order_product in order_products %}
                            <tr>
                                <td>{{ order_product.producttype.id }}</td>
                                <td>{{ order_product.producttype.name }}</td>
                                <td>{{ order_product.quantity }}</td>
                            </tr>
                            {% endfor %}
    
                        </tbody>
                    </table>

            </div>
        </div>        
    </div> 
    <!--End Body-->       
</div>
<!-- container -->
{% endblock %}
{% block extra_javascript %}
<script>
    $(document).ready( function() {
        $('#list_product_order').DataTable().addClass("pagination-rounded");
    } );
    $("#input").val("Test")
</script>
{% endblock%}

src/inventory/templates/manager/orders/list_products.html
{% extends "inventory_base.html" %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block extra_css %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
{% endblock %}

{% block content %}
<!-- Start Content-->
<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    
                </div>
                <h4 class="page-title"><i data-feather="list"></i> Lista de pedido al proveedor: {{ supplier.name }}</h4>
            </div>
        </div>
    </div>     
    <!-- end page title --> 
    <!--Body-->

     <!-- Modal -->
     <div class="modal fade" id="addProduct" tabindex="-1" aria-labelledby="addProductlLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="addProductLabel">Agregar Producto</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <!-- Form -->
            <form method="post", enctype="multipart/form-data0">
                <div class="modal-body">
                    {% csrf_token %}
                        <div class="row">
                            <center>
                                <h4><b> Lista de productos </b> </h4>
                            </center>
                        </div>
                        <br>
                        <!-- Tabla -->
                        <table id="list_product" class="table table-striped table-bordered" style="width:100%">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Nombre</th>
                                    <th>Existencia</th>
                                    <th>Categoria</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for product in products %}
                                <tr style="cursor: pointer;" onclick="display('{{ product.id }}', '{{ product.name }}')">
                                    <td>{{ product.id }}</td>
                                    <td>{{ product.name }}</td>
                                    <td>
                                        {% if product.quantity > product.orderpoint %}
                                            <span class="badge bg-soft-success text-success" style="font-size: 0.85em"><b>{{ product.quantity }}</b></span>
                                        {% else %}
                                            <span class="badge bg-soft-danger text-danger" style="font-size: 0.85em"><b>{{ product.quantity }}</b></span>
                                        {% endif %}
                                    </td>
                                    <td>{{ product.category }}</td>
                                </tr>
                                {% endfor %}
        
                            </tbody>
                        </table>
                        <br>
                        <div class="row">
                            <center>
                                <h4><b> Producto </b> </h4>
                            </center>
                        </div>
                        <br>
                        <!-- Product -->
                        <div class="row">
                            <!-- ID Product -->
                            <div class="col-md-6">
                                <input class="form-control" id="id_product" name="id_product" type="text" readonly required>
                                <small>ID Producto*</small>
                            </div>
                            
                            <!-- Product -->
                            <div class="col-md-6">
                                <input class="form-control" id="product" name="product" type="text" readonly required>
                                <small>Producto*</small>
                            </div>
                        </div>
                        <br>
                        <!-- Catidad a ordenar -->
                        <div class="row">
                            <div class="col-md-6">
                                <label for="lblquantity">Cantidad a ordenar*:</label>
                            </div>
                            
                            <div class="col-sm-6">
                                <input class="form-control" name="quantity" id="quantity" type="number" min="1" placeholder="Cantidad" pattern="[0-9]+" title="Solo Numeros" required>
                                <small>Formato: [0-9]+</small>
                            </div>
                        </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                    <button type="button" class="btn btn-secondary" onclick="clean()">Limpiar</button>
                    <button type="submit" class="btn btn-primary">Agregar</button>
                </div>
            </form>
        </div>
        </div>
    </div>
    <!-- Fin modal -->

    <div class="row" style="padding-left: 3em; padding-right: 3em;">
        <div class="card" style="border-radius: 25px;">
            <div class="card-body p-4">

                <div class="btn-group" role="group" aria-label="Basic outlined example">
                        <!-- Modal -->
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#addProduct">
                            Agregar producto
                        </button>
                    
                        <!-- Modal -->
                        <!-- Button trigger modal -->
                        <a class="btn btn-outline-primary" href="{% url 'send_order_email' %}" onclick="
                        return confirm('Seguro que desea enviar el pedido')">
                            Enviar Pedido
                        </a>

                        <!-- Close -->
                        <!-- Button trigger modal -->
                        <a class="btn btn-outline-danger" href="{% url 'btn_cancel_an_order' order_id %}" onclick="
                        return confirm('Seguro que desea cancelar el pedido')">
                            Cancelar
                        </a>
                </div>

                <div class="row">
                    <center>
                        <h2><b>Lista de productos </b> </h2>
                    </center>
                </div>
                

                <br>
                <div class="row">
                    <h4><b>Pedido: No. </b> {{ order_id }}</h4>
                </div>
                <br>
                    <!-- Tablas -->
                    <table id="list_product_order" class="table table-striped table-bordered" style="width:100%">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Producto</th>
                                <th>Cantidad Solicitada</th>
                                <th> </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for order_product in order_products %}
                            <tr>
                                <td>{{ order_product.producttype.id }}</td>
                                <td>{{ order_product.producttype.name }}</td>
                                <td>{{ order_product.quantity }}</td>
                                <td style="text-align: center;">
                                    <small style="font-size: 1.5em"><a href="{% url 'remove_product' supplier.id order_product.id %}" title="Eliminar" class="delete" onclick="
                                        return confirm('Seguro que deseas remover este producto de la orden')"><i class="fe-trash-2"></i></a></small>      
                                </td>
                            </tr>
                            {% endfor %}
    
                        </tbody>
                    </table>

            </div>
        </div>        
    </div> 
    <!--End Body-->       
</div>
<!-- container -->
{% endblock %}
{% block extra_javascript %}
<script>
    $(document).ready( function() {
        $('#list_product').DataTable().addClass("pagination-rounded");
    } );
    $("#input").val("Test")
</script>
<script>
    $(document).ready( function() {
        $('#list_product_order').DataTable().addClass("pagination-rounded");
    } );
    $("#input").val("Test")
</script>
<script>
    function display(id, name) {
        document.getElementById("id_product").value = id;
        document.getElementById("product").value = name;
    }
    function clean() {
        document.getElementById("id_product").value = '';
        document.getElementById("product").value = '';
        document.getElementById("quantity").value = '';
    }
</script>
{% endblock%}